export const elements = {
  mainContent: document.getElementById('mainContent'),
  searchInput: document.getElementById('searchInput'),
  clearSearch: document.getElementById('clearSearch'),
  searchResults: document.getElementById('searchResults'),
  bookmarkList: document.getElementById('bookmarkList'),
  recentBookmarks: document.getElementById('recentBookmarks'),
  addSection: document.getElementById('addSection'),
  addCurrentBtn: document.getElementById('addCurrentBtn'),
  addForm: document.getElementById('addForm'),
  cancelAdd: document.getElementById('cancelAdd'),
  bookmarkName: document.getElementById('bookmarkName'),
  bookmarkUrl: document.getElementById('bookmarkUrl'),
  bookmarkCategory: document.getElementById('bookmarkCategory'),
  bookmarkLevel: document.getElementById('bookmarkLevel'),
  bookmarkDesc: document.getElementById('bookmarkDesc'),
  submitBookmark: document.getElementById('submitBookmark'),
  addCategoryBtn: document.getElementById('addCategoryBtn'),
  categoryModal: document.getElementById('categoryModal'),
  closeCategoryModal: document.getElementById('closeCategoryModal'),
  newCategoryName: document.getElementById('newCategoryName'),
  newCategoryParent: document.getElementById('newCategoryParent'),
  newCategoryLevel: document.getElementById('newCategoryLevel'),
  submitCategory: document.getElementById('submitCategory'),
  duplicateWarning: document.getElementById('duplicateWarning'),
  duplicateName: document.getElementById('duplicateName'),
  i18nToggle: document.getElementById('i18nToggle'),
  themeToggle: document.getElementById('themeToggle'),
  toast: document.getElementById('toast'),
  openSite: document.getElementById('openSite'),
  openSettings: document.getElementById('openSettings'),
  notConnected: document.getElementById('notConnected'),
  loading: document.getElementById('loading')
}

export const i18n = {
  zh: {
    openSite: '打开导航站',
    settings: '设置',
    toggleLang: '切换语言',
    toggleTheme: '切换日/夜模式',
    notConnectedTip: '请先配置服务器地址',
    goToSettings: '前往设置',
    addCurrent: '添加当前页面',
    searchPlaceholder: '搜索书签...',
    recentVisit: '最近书签',
    invalidUrl: '网址无效',
    addBookmark: '添加书签',
    urlStored: '该网址已收藏：',
    name: '名称',
    url: '网址',
    category: '分类',
    level: '可见等级',
    level0: '游客可见',
    level1: '注册用户',
    level2: 'VIP 用户',
    level3: '仅管理员',
    description: '描述 (可选)',
    descPlaceholder: '简短描述...',
    save: '保存',
    newCategory: '新建分类',
    categoryName: '分类名称',
    catPlaceholder: '输入分类名称',
    create: '创建',
    noResults: '暂无书签',
    loadFailed: '加载失败',
    noMatch: '未找到匹配的书签',
    searchResult: '搜索结果',
    webOnly: '只能添加网页，请切换到普通网页后重试',
    duplicateAlert: '该页面已收藏，无法重复添加',
    infoFetchFailed: '无法获取当前页面信息',
    fillRequired: '请填写必要信息',
    addSuccess: '书签添加成功',
    addFailed: '添加失败',
    duplicateIn: '已存在于',
    catAddSuccess: '分类创建成功',
    catAddFailed: '创建失败',
    newCatTip: '新建分类',
    tokenInvalid: '登录令牌无效。用户名已保留，请在设置中重新输入密码。',
    tokenExpired: '登录已过期。用户名已保留，请在设置中重新输入密码。',
    edit: '编辑',
    delete: '删除',
    confirmDelete: '确定要删除这个书签吗？',
    updateSuccess: '更新成功',
    updateFailed: '更新失败',
    deleteSuccess: '删除成功',
    deleteFailed: '删除失败',
    parentCategory: '父级分类',
    rootCategory: '无 (根分类)',
    unknownCategory: '未知分类'
  },
  en: {
    openSite: 'Open StarNav',
    settings: 'Settings',
    toggleLang: 'Switch Language',
    toggleTheme: 'Toggle light/dark mode',
    notConnectedTip: 'Please configure server address first',
    goToSettings: 'Go to Settings',
    addCurrent: 'Add Current Page',
    searchPlaceholder: 'Search bookmarks...',
    recentVisit: 'Recent bookmarks',
    invalidUrl: 'Invalid URL',
    addBookmark: 'Add Bookmark',
    urlStored: 'URL already stored: ',
    name: 'Name',
    url: 'URL',
    category: 'Category',
    level: 'Visibility',
    level0: 'Guest',
    level1: 'User',
    level2: 'VIP',
    level3: 'Admin Only',
    description: 'Description (Optional)',
    descPlaceholder: 'Short description...',
    save: 'Save',
    newCategory: 'New Category',
    categoryName: 'Category Name',
    catPlaceholder: 'Enter category name',
    create: 'Create',
    noResults: 'No bookmarks',
    loadFailed: 'Failed to load',
    noMatch: 'No matching bookmarks',
    searchResult: 'Search results',
    webOnly: 'Webpages only. Please switch tabs and try again.',
    duplicateAlert: 'URL already exists, cannot add duplicate',
    infoFetchFailed: 'Failed to fetch page info',
    fillRequired: 'Please fill in required fields',
    addSuccess: 'Bookmark added successfully',
    addFailed: 'Failed to add',
    duplicateIn: 'Already exists in',
    catAddSuccess: 'Category created successfully',
    catAddFailed: 'Failed to create',
    newCatTip: 'New Category',
    tokenInvalid: 'Invalid token. Username kept — re-enter password in Settings.',
    tokenExpired: 'Session expired. Username kept — re-enter password in Settings.',
    edit: 'Edit',
    delete: 'Delete',
    confirmDelete: 'Are you sure you want to delete this bookmark?',
    updateSuccess: 'Updated successfully',
    updateFailed: 'Failed to update',
    deleteSuccess: 'Deleted successfully',
    deleteFailed: 'Failed to delete',
    parentCategory: 'Parent Category',
    rootCategory: 'None (Root)',
    unknownCategory: 'Unknown'
  }
}

export const createPopupState = () => ({
  currentLang: 'zh',
  currentThemeMode: 'light',
  config: { serverUrl: '', token: '' },
  categories: [],
  debounceTimer: null,
  currentEditingId: null
})
